name: Deploy React Vite App

on:
  push:
    branches:
      - chakra

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -p 22 -H 102.127.29.15 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          rsync -avz -e "ssh -p 22 -i ~/.ssh/deploy_key" \
            dist/ root@102.127.29.15:/var/www/html/

      - name: Reload Nginx
        run: |
          ssh -p 22 -i ~/.ssh/deploy_key root@102.127.29.15 'sudo systemctl reload nginx'
