name: Deploy Vite App

on:
  push:
    branches:
      - chakra
  pull_request:
    branches:
      - chakra

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build the Vite app
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: |
          echo "Running npm run build"
          npm run build
          echo "Build completed"
          ls -la dist/

      - name: Deploy and configure server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DEPLOY_PATH: /var/www/fota-frontend/dist # Changed to match Nginx config
          SERVER_IP: 103.209.145.218
        run: |
          # Setup SSH key
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          # Create directory if it doesn't exist
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no root@$SERVER_IP "mkdir -p $DEPLOY_PATH"

          # Deploy using rsync
          rsync -avz -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
            dist/ root@$SERVER_IP:$DEPLOY_PATH
            
          # Set permissions and restart Nginx
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no root@$SERVER_IP "
            # Set proper permissions
            chown -R www-data:www-data $DEPLOY_PATH
            chmod -R 755 $DEPLOY_PATH
            
            # Test Nginx config
            nginx -t && systemctl restart nginx
            
            # Show deployed files
            echo 'Deployed files:'
            ls -la $DEPLOY_PATH
            
            # Show index.html content to verify
            echo 'Index.html exists:'
            ls -la $DEPLOY_PATH/index.html
          "
