name: CI/CD

on:
  push:
    branches: ["chakra"]
  pull_request:
    branches: ["chakra"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm ci
      - run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 103.209.145.218 >> ~/.ssh/known_hosts
          ssh www-data@103.209.145.218 'cd /var/www/fota-frontend/dist && git pull origin chakra && npm install --production && pm2 restart fota-frontend'
