name: Deploy Vite App

on:
  push:
    branches:
      - chakra # Adjust if deploying from a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clear Node modules (optional for a fresh build)
        run: rm -rf node_modules

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Updated to Node.js 18

      - name: Install dependencies
        run: npm install

      - name: Debug build output (list dist contents)
        run: ls -la dist/ # This will list the build files to confirm they're being generated

      - name: Build the Vite app
        run: npm run build

      - name: Debug build output (after build)
        run: ls -la dist/ # This will list the build files after the build process to check if changes are applied

      - name: Upload production-ready files to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Set up SSH key
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          # Sync the build files to the server's target directory
          rsync -avz -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
            dist/ root@103.209.145.218:/var/www/fota-frontend/

      - name: Restart Nginx
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no root@103.209.145.218 \
            "sudo systemctl restart nginx"
