name: CI/CD Pipeline

on:
  push:
    branches:
      - chakra # Trigger deployment when pushing to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest # This will use the latest Ubuntu image for the GitHub runner

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js (use the appropriate version for your project)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Adjust Node.js version based on your needs

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run the build process
      - name: Build the project
        run: npm run build

      # Deploy to the server
      - name: Deploy to Server
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key" dist/ root@103.209.145.218:/var/www/fota-frontend
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # Restart Nginx to serve the updated build
      - name: Restart Nginx
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no root@103.209.145.218 \
            "sudo systemctl restart nginx"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
