name: Deploy React Vite App

on:
  push:
    branches:
      - chakra  # The branch that triggers deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH keys to authenticate with the server
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 102.127.29.15 >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Set up Node.js environment and install dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      # Step 4: Build the application
      - name: Build the application
        run: npm run build

      # Step 5: Deploy to the server (rsync command to copy the build files)
      - name: Deploy to server
        run: |
          rsync -avz -e "ssh -p 22 -i ~/.ssh/id_rsa" \
            dist/ root@102.127.29.15:/var/www/html/

      # Step 6: Reload Nginx to apply the new build
      - name: Reload Nginx
        run: |
          ssh -p 22 -i ~/.ssh/id_rsa root@102.127.29.15 'sudo systemctl reload nginx'
