name: Deploy Vite App

on:
  push:
    branches:
      - chakra
  pull_request:
    branches:
      - chakra

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Clean local environment
        run: |
          rm -rf dist
          rm -rf node_modules
          echo "Cleaned local build artifacts"

      - name: Install dependencies
        run: npm install

      - name: Build the Vite app
        run: |
          echo "Running npm run build"
          npm run build
          echo "Build completed"
          ls -la dist/

      - name: Deploy to production server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DEPLOY_PATH: /var/www/fota-frontend/
          SERVER_IP: 103.209.145.218
        run: |
          # Setup SSH key
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          # Clean remote directory first
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no root@$SERVER_IP "rm -rf $DEPLOY_PATH/*"

          # Deploy using rsync
          rsync -avz --delete -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
            dist/ root@$SERVER_IP:$DEPLOY_PATH

          # Set proper permissions and ownership
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no root@$SERVER_IP "
            chown -R www-data:www-data $DEPLOY_PATH
            chmod -R 755 $DEPLOY_PATH
            
            # Test Nginx configuration
            nginx -t
            
            # Restart Nginx if config test passes
            systemctl restart nginx
            
            # Check Nginx status
            systemctl status nginx
            
            # Check error logs
            tail -n 50 /var/log/nginx/error.log
          "
