name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger deployment when pushing to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest # This will use the latest Ubuntu image for the GitHub runner

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js (use the appropriate version for your project)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Adjust Node.js version based on your needs

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Check if dist directory exists before build
      - name: Check if dist directory exists before build
        run: |
          echo "Checking if dist/ exists before build"
          ls -la || true  # This step will show the project root content so be it

      # Build the Vite app
      - name: Build the Vite app
        run: |
          echo "Running npm run build"
          npm run build
          echo "Build completed"

      # Check if dist directory exists after build
      - name: Check if dist directory exists after build
        run: |
          echo "Checking if dist/ exists after build"
          ls -la dist/ || echo "dist/ does not exist"

      # Setup SSH key and known hosts
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H 103.209.145.218 >> ~/.ssh/known_hosts

      # Upload production-ready files to the server
      - name: Upload production-ready files to server
        run: |
          echo "Syncing files to the server"
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key" dist/ root@103.209.145.218:/var/www/fota-frontend

      # Restart Nginx to serve the updated build
      - name: Restart Nginx
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no root@103.209.145.218 \
            "sudo systemctl restart nginx"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
